# This workflow will do a clean installation of node dependencies using PNPM, cache/restore them, build the source code, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js pnpm CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    # Setup PNPM
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8.x # Adjust the version based on your project needs

    # Install dependencies using PNPM
    - run: pnpm install

    # Run build and tests using PNPM
    - run: pnpm run polyfill
    - run: pnpm run build --if-present
    - run: pnpm test
